---
version: 2.1

executors:
  build-executor:
    docker:
      - image: quay.io/labmonkeys/vmbuilder:1.9.2.b63

commands:
  make-image:
    description: "Build OVA image and publish from main branch"
    parameters:
      workdir:
        default: "~/project"
        type: string
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive ansible
      - run:
          name: Build OVA image and publish from main branch
          command: |
            cd << parameters.workdir >> && pwd
            make

workflows:
  ova-workflow:
    jobs:
      - build-core
      - build-minion
      - build-sentinel

jobs:
  build-core:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./core"
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - store_artifacts:
          path: image

  build-minion:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./minion"
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - store_artifacts:
          path: image

  build-sentinel:
    executor: build-executor
    steps:
      - make-image:
          workdir: "./sentinel"
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - store_artifacts:
          path: image
